# Generated by Django 2.2.5 on 2019-09-26 13:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carticle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
