# Generated by Django 2.2.6 on 2019-10-05 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carticle', '0002_auto_20191005_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='article_dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
