# Generated by Django 2.2.6 on 2019-10-06 18:51

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('carticle', '0003_article_dislikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
